### ISSUE TITLE
use this engine with threejs in vue  

### ISSUE THREAD

**Issue by francis9527** [samrun0/ion-3D-Engine#7]
ion-3d-engine.module.js:2  Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at v.eval (ion-3d-engine.module.js:2:1)
    at v.dispatchEvent (three.module.js:266:1)
    at HTMLDocument.o (ion-3d-engine.module.js:2:1)

**Comment by francis9527** [comment]
How to remove the prompt "click to start"?

**Comment by samrun0** [comment]
Hi @francis9527, 

You can set `showInstructions: false` in controlOptions when creating an Engine instance:

```ts
ION.Engine({
    canvas: HTMLCanvasElement,
    scene: THREE.Scene,
    control: string,
    controlOptions: {
        vrTeleportEnabled: boolean,
        vrTeleportList: Array,
        framebufferScaleFactor: number,
        showInstructions: false, // <<<<<<<<<<< Here
    },
    vrEnabled: boolean,
    graphicsOptions: object,
    fullScreen: boolean,
    stats: boolean,
    camera: THREE.Camera,
})
```

One similar example: https://samrun0.github.io/gui-examples/gui-curved.html

We're updating the docs to add these additional options. 

For your Vue question, we have a similar example for ReactJS here: https://github.com/samrun0/samrun0.github.io/blob/main/gui-examples/reactjs/src/index.js

At this point, I can suggest to make sure the document is already fully loaded (mounted()) before calling the ion code.
